### ISSUE TITLE
using this dependency with android 11

### ISSUE THREAD

**Issue by shlomi-ts** [nodes-android/filepicker#10]
when I'm going to FilePickerActivity from **android 11** 
`val intent = Intent(activity, FilePickerActivity::class.java)
        intent.putExtra(FilePickerConstants.TYPE, FilePickerConstants.MIME_IMAGE)
        startActivityForResult(intent, READ_REQUEST_CODE)`

I experience a crash - 
`java.lang.RuntimeException: Unable to start activity ComponentInfo{dk.nodes.filepicker.FilePickerActivity}: java.lang.IllegalArgumentException: Unsupported MIME type image/jpg
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)`

**Comment by Jitendrasahu999** [comment]
**Yes, i am not use this libaray on Android 11 Please resolve......As soon as posible**

when I'm going to FilePickerActivity from android 11
val intent = Intent(activity, FilePickerActivity::class.java) intent.putExtra(FilePickerConstants.TYPE, FilePickerConstants.MIME_IMAGE) startActivityForResult(intent, READ_REQUEST_CODE)

I experience a crash -
java.lang.RuntimeException: Unable to start activity ComponentInfo{dk.nodes.filepicker.FilePickerActivity}: java.lang.IllegalArgumentException: Unsupported MIME type image/jpg at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)

Jitendra Sahu

**Comment by Jitendrasahu999** [comment]
Yes, i am not use this libaray on Android 11 Please resolve......As soon as posible

when I'm going to FilePickerActivity from android 11
val intent = Intent(activity, FilePickerActivity::class.java) intent.putExtra(FilePickerConstants.TYPE, FilePickerConstants.MIME_IMAGE) startActivityForResult(intent, READ_REQUEST_CODE)

I experience a crash -
java.lang.RuntimeException: Unable to start activity ComponentInfo{dk.nodes.filepicker.FilePickerActivity}: java.lang.IllegalArgumentException: Unsupported MIME type image/jpg at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)

Jitendra Sahu

**Comment by Jitendrasahu999** [comment]
Yes, i am not use this libaray on Android 11 Please resolve......As soon as posible

when I'm going to FilePickerActivity from android 11
val intent = Intent(activity, FilePickerActivity::class.java) intent.putExtra(FilePickerConstants.TYPE, FilePickerConstants.MIME_IMAGE) startActivityForResult(intent, READ_REQUEST_CODE)

I experience a crash -
java.lang.RuntimeException: Unable to start activity ComponentInfo{dk.nodes.filepicker.FilePickerActivity}: java.lang.IllegalArgumentException: Unsupported MIME type image/jpg at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)

Jitendra Sahu

**Comment by Jitendrasahu999** [comment]
Yes, i am not use this libaray on Android 11 Please resolve......As soon as posible

when I'm going to FilePickerActivity from android 11
val intent = Intent(activity, FilePickerActivity::class.java) intent.putExtra(FilePickerConstants.TYPE, FilePickerConstants.MIME_IMAGE) startActivityForResult(intent, READ_REQUEST_CODE)

I experience a crash -
java.lang.RuntimeException: Unable to start activity ComponentInfo{dk.nodes.filepicker.FilePickerActivity}: java.lang.IllegalArgumentException: Unsupported MIME type image/jpg at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)

Jitendra Sahu

**Comment by Jitendrasahu999** [comment]
Yes, i am not use this libaray on Android 11 Please resolve......As soon as posible

when I'm going to FilePickerActivity from android 11
val intent = Intent(activity, FilePickerActivity::class.java) intent.putExtra(FilePickerConstants.TYPE, FilePickerConstants.MIME_IMAGE) startActivityForResult(intent, READ_REQUEST_CODE)

I experience a crash -
java.lang.RuntimeException: Unable to start activity ComponentInfo{dk.nodes.filepicker.FilePickerActivity}: java.lang.IllegalArgumentException: Unsupported MIME type image/jpg at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)

Jitendra Sahu
